name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #编译
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          check-latest: true

      - name: Build
        run: go build -v ./...
  #执行测试
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          check-latest: true

      - name: Test
        run: go test -run=Test .

      - name: Benchmark
        run: go test -bench=Benchmark -benchmem .
